USE [master]
GO

/****** Object:  Database [Photography]    Script Date: 02/19/2013 07:58:11 ******/
CREATE DATABASE [Photography] ON  PRIMARY 
( NAME = N'Photography', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\Photography.mdf' , SIZE = 2048KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Photography_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\Photography_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Photography] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Photography].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Photography] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Photography] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Photography] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Photography] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Photography] SET ARITHABORT OFF 
GO

ALTER DATABASE [Photography] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Photography] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Photography] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Photography] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Photography] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Photography] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Photography] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Photography] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Photography] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Photography] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Photography] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Photography] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Photography] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Photography] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Photography] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Photography] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Photography] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Photography] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Photography] SET  READ_WRITE 
GO

ALTER DATABASE [Photography] SET RECOVERY FULL 
GO

ALTER DATABASE [Photography] SET  MULTI_USER 
GO

ALTER DATABASE [Photography] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Photography] SET DB_CHAINING OFF 
GO


